const countryList = {
    AED: "AE",
    AFN: "AF",
    ALL: "AL",
    AUD: "AU",
    EUR: "ER",
    GMD: "GM",
    GNF: "GN",
    INR: "IN",
    ISK: "IS",
    JMD: "JM",
    JPY: "JP",
    KZT: "KZ",
    MXN: "MX",
    MYR: "MY",
    NZD: "NZ",
    PKR: "PK",
    SAR: "SA",
    SBD: "SB",
    SDG: "SD",
    SLL: "SL",
    STD: "ST",
    SZL: "SZ",
    USD: "US"
  };